"""empty message

Revision ID: 3ae56ae3765b
Revises: bfc42ac7112d
Create Date: 2023-11-14 14:55:55.902351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae56ae3765b'
down_revision = 'bfc42ac7112d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('height', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_column('height')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
